name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: org.emoflon.ilp.updatesite
          path: org.emoflon.ilp.updatesite/target/org.emoflon.ilp.updatesite-*.zip

  doc:
    runs-on: [ubuntu-22.04]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4
      - name: Create JavaDoc with Maven
        run: mvn --batch-mode --update-snapshots site
      - name: Upload doc artifact
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: org.emoflon.ilp/target/site

  test:
    runs-on: [ubuntu-22.04]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install GLPK
        run: |
          sudo apt-get install -yq glpk-utils libglpk-dev glpk-doc libglpk-java libglpk40
          sudo cp /usr/lib/x86_64-linux-gnu/jni/libglpk_java.* /usr/lib/
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots clean -Dtest=BasicTest,GlpkTest,SolverTest -DfailIfNoTests=false verify
